### ISSUE TITLE
能否支持拉取每日用电信息

### ISSUE THREAD

**Issue by helloworlde** [georgezhao2010/bj_sgcc_energy#10]
公众号目前可以支持查询 30 日内的用电信息，请问是否可以支持；感谢

**Comment by georgezhao2010** [comment]
> 公众号目前可以支持查询 30 日内的用电信息，请问是否可以支持；感谢

你说的是北京国网电力的公众号吗？我找来找去没找到可以按日查询用电信息啊。可以给我指明一下是哪里吗

**Comment by helloworlde** [comment]
> > 公众号目前可以支持查询 30 日内的用电信息，请问是否可以支持；感谢
> 
> 你说的是北京国网电力的公众号吗？我找来找去没找到可以按日查询用电信息啊。可以给我指明一下是哪里吗

是的，国网北京电力-微营业厅-自助服务-日电量查询，如图所示
![WechatIMG238](https://user-images.githubusercontent.com/13172836/173479749-db91e7b2-7bf8-4dba-8a15-b7e4fe42e4f4.jpeg)
