### ISSUE TITLE
能不能根据2023.6再更新一版本

### ISSUE THREAD

**Issue by RayL1234** [georgezhao2010/bj_sgcc_energy#16]
现在不可用了

**Comment by lion00** [comment]
+1

**Comment by Messiforever** [comment]
请求大佬再更新一版

**Comment by ElegantWoo** [comment]
再更一版吧
估计接口又变了

**Comment by zc1342303** [comment]
+1

**Comment by gonghao** [comment]
可以简单修改一下源码就能正常运行

找到 `/config/custom_components/bj_sgcc_energy/sgcc.py` 257 行，`await asyncio.wait(tasks)` 修改成 `await asyncio.gather(*tasks)`

**Comment by ElegantWoo** [comment]
> 可以简单修改一下源码就能正常运行
> 
> 找到 `/config/custom_components/bj_sgcc_energy/sgcc.py` 257 行，`await asyncio.wait(tasks)` 修改成 `await asyncio.gather(*tasks)`

可以了
但是不是很稳定
