### ISSUE TITLE
阶梯第二阶段没有数据

### ISSUE THREAD

**Issue by ocerot** [georgezhao2010/bj_sgcc_energy#3]
非常感谢开发了这么好用的插件，但是我安装后有几个实体没有出现，
sensor.XXXXXXXXXX_current_level
sensor.XXXXXXXXXX_current_level_consume
sensor.XXXXXXXXXX_current_level_remain
sensor.XXXXXXXXXX_current_pgv_type
sensor.XXXXXXXXXX_current_price

家里是阶梯用电，目前处于第二阶梯用电中，电费余额、年度用电、本季度电费、历史用电量都没问题，就是关于阶梯的实体没有出来。

**Comment by georgezhao2010** [comment]
请下载v0.1.1测试并反馈

**Comment by ocerot** [comment]
测试成功，数据正常，感谢感谢
