### ISSUE TITLE
getToken response got error

### ISSUE THREAD

**Issue by nicedc** [georgezhao2010/bj_sgcc_energy#6]
此错误来自自定义集成。

Logger: custom_components.bj_sgcc_energy.sgcc
Source: custom_components/bj_sgcc_energy/sgcc.py:67
Integration: 北京用电信息查询 (documentation, issues)
First occurred: 10:08:34 (1 occurrences)
Last logged: 10:08:34

getToken response got error: HTTPConnectionPool(host='weixin.bj.sgcc.com.cn', port=80): Max retries exceeded with url: /ott/app/auth/authorize?target=M_YECX (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3cbdd8a90>: Failed to establish a new connection: [Errno -3] Try again'))

这个是哪里有问题呀  还有会考虑把传感器改一下介入官方的能源吗  现在的能源里找不到对应的传感器（不太懂语言）

**Comment by zhtrx** [comment]
M_YECX   ->    M_WYYT
