### ISSUE TITLE
能否支持其他省市？

### ISSUE THREAD

**Issue by wolnlow** [georgezhao2010/bj_sgcc_energy#7]
不知能否支持其他省市，做成通用的？

**Comment by bbyamap** [comment]
> 

估计难。。。浙江国网电力的公众号跟北京就不一样。。

**Comment by georgezhao2010** [comment]
> 不知能否支持其他省市，做成通用的？

各个省市应该都是自己找第三方开发的，因此各省市都完全不一样，所以这个玩意没法通用。
